@echo off
echo Dang khoi dong moi truong ao...
call venv\Scripts\activate
echo Dang kiem tra thu vien (install Tesseract if needed)...
pip install -r requirements.txt
echo Dang chay Giao dien Sudoku Solver V4...
python app_ui.py
pause
